### ISSUE TITLE
Easy way to install blogger template on blogspot

### ISSUE THREAD

**Issue by faizzzsheikh** [zkreations/hamlet#2]
Hi.. do you have a guide on how can I install your template on blogger?

**Comment by danieIabel** [comment]
Simply copy all the compiled code and paste it into Blogger's HTML editor: https://raw.githubusercontent.com/zkreations/hamlet/main/dist/hamlet.xml

**Comment by danieIabel** [comment]
The goal of this repository is not the theme itself, it is to provide a more pleasant environment for developing a theme on Blogger.
